// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcutnqyipkilxfltzvbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdXRucXlpcGtpbHhmbHR6dmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDYzNjQsImV4cCI6MjA2MTc4MjM2NH0.0TTL0Bktq4i0OEnw2-CDO896wM-5NJH2tWOFiUMfo84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);